In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import zipfile

In [2]:
with zipfile.ZipFile('../data/archive.zip', 'r') as f:
    print(f'The archive contains: \n{f.namelist()}')
    f.extractall(path='../data/')

The archive contains:
['adhdata.csv']

In [3]:
dataset = pd.read_csv('../data/adhdata.csv')

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2166383 entries, 0 to 2166382
Data columns (total 21 columns):
 #   Column  Dtype
---  ------  -----
 0   Fp1     float64
 1   Fp2     float64
 2   F3      float64
 3   F4      float64
 4   C3      float64
 5   C4      float64
 6   P3      float64
 7   P4      float64
 8   O1      float64
 9   O2      float64
 10  F7      float64
 11  F8      float64
 12  T7      float64
 13  T8      float64
 14  P7      float64
 15  P8      float64
 16  Fz      float64
 17  Cz      float64
 18  Pz      float64
 19  Class   object
 20  ID      object
dtypes: float64(19), object(2)
memory usage: 347.1+ MB

In [6]:
dataset[12:17]

,Fp1,Fp2,F3,F4,C3,C4,P3,P4,O1,O2,...,F8,T7,T8,P7,P8,Fz,Cz,Pz,Class,ID
12,930.0,1001.0,236.0,437.0,16.0,384.0,-278.0,163.0,52.0,200.0,...,384.0,236.0,420.0,-20.0,273.0,402.0,367.0,15.0,ADHD,v10p
13,1106.0,1001.0,494.0,543.0,347.0,531.0,89.0,310.0,52.0,163.0,...,420.0,420.0,457.0,163.0,273.0,473.0,402.0,191.0,ADHD,v10p
14,860.0,684.0,273.0,297.0,163.0,310.0,-57.0,89.0,310.0,236.0,...,273.0,310.0,310.0,52.0,163.0,332.0,226.0,-19.0,ADHD,v10p
15,789.0,719.0,273.0,367.0,163.0,420.0,-20.0,273.0,126.0,273.0,...,236.0,347.0,420.0,163.0,273.0,332.0,367.0,156.0,ADHD,v10p
16,860.0,789.0,310.0,332.0,200.0,347.0,126.0,200.0,163.0,236.0,...,273.0,310.0,310.0,126.0,163.0,332.0,191.0,15.0,ADHD,v10p

In [7]:
shuffled_data = dataset.sample(frac=1, random_state=37).reset_index(drop=True)

In [8]:
shuffled_data[12:17]

,Fp1,Fp2,F3,F4,C3,C4,P3,P4,O1,O2,...,F8,T7,T8,P7,P8,Fz,Cz,Pz,Class,ID
12,85.0,15.0,-20.0,-19.0,-20.0,273.0,16.0,-131.0,-57.0,-241.0,...,52.0,200.0,-57.0,-20.0,-57.0,-90.0,-231.0,-231.0,ADHD,v15p
13,332.0,367.0,347.0,402.0,200.0,236.0,-57.0,126.0,310.0,310.0,...,384.0,-903.0,-57.0,16.0,126.0,332.0,-19.0,15.0,Control,v49p
14,-19.0,156.0,-20.0,226.0,-20.0,200.0,-241.0,52.0,-167.0,-57.0,...,163.0,-20.0,163.0,-94.0,163.0,50.0,121.0,-195.0,Control,v149
15,-90.0,50.0,16.0,15.0,16.0,16.0,89.0,16.0,89.0,52.0,...,89.0,52.0,52.0,16.0,89.0,-19.0,-55.0,121.0,ADHD,v263
16,50.0,156.0,89.0,156.0,163.0,236.0,236.0,126.0,347.0,163.0,...,126.0,89.0,163.0,126.0,236.0,85.0,191.0,156.0,ADHD,v198